# pylint: disable=C0114

# APP
APP_INSTANCE = None
NAV_INSTANCE = None
ACTIVE_PAGE = None
NAME = "LuxeCrafted"
RESOLUTION = "1280x720"
USER_LOGIN = 1

# COLOR
COLOR_LIGHT = "#F3F3F3"
COLOR_SECONDARY_LIGHT = "#DDDDDD"
COLOR_DARK = "#1A1A1A"
COLOR_SECONDARY_DARK = "#2A2A2A"
COLOR_PRIMARY = "#FFD700"
COLOR_DANGER = "#BB2124"
